### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by takarabune** [mikaelho/pythonista-markdownview#8]
Hi, 

There is no license associated with MarkdownView. Do you have any restrictions on its use? 

I’d like to use it in a project, possibly edit it and add the fork to that project’s repository.

**Comment by mikaelho** [comment]
No restrictions whatsoever. If I remember correctly, this might benefit from some modernising, both in terms of Python version and Pythonista capabilities.

**Comment by takarabune** [comment]
Thanks. 
It runs under 3.10, after Pythonista’s 2to3 automated script. 
The demo just seems to need the explicit encoding=“utf8” in the open statements. 

As I know very little about Python or Pythonista, I’m loath to touch the main branch.
